// Auto-generated by scripts/ingest.mjs --id recife-v1
// Do not edit manually. Re-run ingest.mjs to regenerate.

export type RetrievalChunkArtifact = {
  chunkId: string
  docId: string
  city: string
  title: string
  category: 'attraction' | 'neighborhood' | 'food_cafe' | 'logistics'
  region: string
  summary: string
  content: string
  snippet: string
  tags: string[]
  source: string
  updatedAt: string
}

export const recifeV1Chunks: RetrievalChunkArtifact[] = [
  {
    "chunkId": "recife-attraction-marco-zero-chunk-1",
    "docId": "recife-attraction-marco-zero",
    "city": "Recife",
    "title": "Marco Zero",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Praca historica e ponto de partida comum para visitar o centro antigo.",
    "content": "O Marco Zero fica na Praca Rio Branco, no bairro do Recife Antigo. O local concentra movimento de visitantes, feiras sazonais e acesso facil para caminhar pela area historica e pelos armazens culturais proximos.",
    "snippet": "Praca historica e ponto de partida comum para visitar o centro antigo. O Marco Zero fica na Praca Rio Branco, no bairro do Recife Antigo. O local concentra movimento de visitantes, feiras sazonais e acesso facil para caminhar pela area historica e pelos armazens culturais proximos.",
    "tags": [
      "centro historico",
      "recife antigo",
      "passeio a pe"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-attraction-cais-do-sertao-chunk-1",
    "docId": "recife-attraction-cais-do-sertao",
    "city": "Recife",
    "title": "Cais do Sertao",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Museu interativo focado na cultura nordestina e no universo de Luiz Gonzaga.",
    "content": "O Cais do Sertao oferece exposicoes interativas, recursos audiovisuais e experiencias sobre musica, territorio e cotidiano do sertao. Fica em area central do Recife Antigo e costuma ser combinado com outros pontos do bairro.",
    "snippet": "Museu interativo focado na cultura nordestina e no universo de Luiz Gonzaga. O Cais do Sertao oferece exposicoes interativas, recursos audiovisuais e experiencias sobre musica, territorio e cotidiano do sertao. Fica em area central do Recife Antigo e costuma ser combinado com outros pontos do bairro.",
    "tags": [
      "museu",
      "cultura",
      "interativo"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-attraction-instituto-ricardo-brennand-chunk-1",
    "docId": "recife-attraction-instituto-ricardo-brennand",
    "city": "Recife",
    "title": "Instituto Ricardo Brennand",
    "category": "attraction",
    "region": "Varzea",
    "summary": "Complexo cultural com museu, pinacoteca e area externa ampla.",
    "content": "O Instituto Ricardo Brennand reune colecoes de arte, biblioteca e um conjunto arquitetonico inspirado em castelo. O deslocamento ate a Varzea costuma demandar mais tempo em comparacao com atracoes centrais.",
    "snippet": "Complexo cultural com museu, pinacoteca e area externa ampla. O Instituto Ricardo Brennand reune colecoes de arte, biblioteca e um conjunto arquitetonico inspirado em castelo. O deslocamento ate a Varzea costuma demandar mais tempo em comparacao com atracoes centrais.",
    "tags": [
      "museu",
      "arte",
      "historia"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-neighborhood-recife-antigo-chunk-1",
    "docId": "recife-neighborhood-recife-antigo",
    "city": "Recife",
    "title": "Recife Antigo",
    "category": "neighborhood",
    "region": "Centro",
    "summary": "Area com concentracao de museus, praca historica e polos culturais.",
    "content": "Recife Antigo concentra pontos como Marco Zero, Paco do Frevo e Cais do Sertao. Para quem quer otimizar deslocamentos, vale reservar um periodo continuo para explorar o bairro a pe e reduzir trocas de transporte.",
    "snippet": "Area com concentracao de museus, praca historica e polos culturais. Recife Antigo concentra pontos como Marco Zero, Paco do Frevo e Cais do Sertao. Para quem quer otimizar deslocamentos, vale reservar um periodo continuo para explorar o bairro a pe e reduzir trocas de transporte.",
    "tags": [
      "bairro",
      "centro",
      "museus"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-neighborhood-boa-viagem-chunk-1",
    "docId": "recife-neighborhood-boa-viagem",
    "city": "Recife",
    "title": "Boa Viagem",
    "category": "neighborhood",
    "region": "Zona Sul",
    "summary": "Area com praia urbana, calcadao e alta oferta de servicos.",
    "content": "Boa Viagem combina praia urbana com rede de restaurantes, hospedagem e comercio. E comum usar o bairro como base logistica por causa da oferta de transporte e da proximidade com o aeroporto.",
    "snippet": "Area com praia urbana, calcadao e alta oferta de servicos. Boa Viagem combina praia urbana com rede de restaurantes, hospedagem e comercio. E comum usar o bairro como base logistica por causa da oferta de transporte e da proximidade com o aeroporto.",
    "tags": [
      "praia",
      "zona sul",
      "hospedagem"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-food-cafe-oficina-do-sabor-chunk-1",
    "docId": "recife-food-cafe-oficina-do-sabor",
    "city": "Recife",
    "title": "Oficina do Sabor",
    "category": "food_cafe",
    "region": "Alto da Se",
    "summary": "Restaurante conhecido em Olinda e frequentemente incluIdo em bate-volta saindo do Recife.",
    "content": "A Oficina do Sabor fica em Olinda, proximo ao Alto da Se, e aparece em roteiros gastronomicos combinados com passeio historico. Para quem esta hospedado no Recife, vale considerar tempo de deslocamento para ida e volta.",
    "snippet": "Restaurante conhecido em Olinda e frequentemente incluIdo em bate-volta saindo do Recife. A Oficina do Sabor fica em Olinda, proximo ao Alto da Se, e aparece em roteiros gastronomicos combinados com passeio historico. Para quem esta hospedado no Recife, vale considerar tempo de deslocamento para ida e volta.",
    "tags": [
      "gastronomia",
      "olinda",
      "bate-volta"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-food-cafe-cafe-jaqueira-chunk-1",
    "docId": "recife-food-cafe-cafe-jaqueira",
    "city": "Recife",
    "title": "Cafe na Jaqueira",
    "category": "food_cafe",
    "region": "Jaqueira",
    "summary": "Opcao de cafe e lanche em area residencial com movimento diurno.",
    "content": "A regiao da Jaqueira oferece cafes e padarias para pausas de meio de tarde. Pode ser uma boa alternativa para um ritmo mais tranquilo entre atividades mais longas do dia.",
    "snippet": "Opcao de cafe e lanche em area residencial com movimento diurno. A regiao da Jaqueira oferece cafes e padarias para pausas de meio de tarde. Pode ser uma boa alternativa para um ritmo mais tranquilo entre atividades mais longas do dia.",
    "tags": [
      "cafe",
      "lanche",
      "ritmo tranquilo"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-logistics-airport-boa-viagem-chunk-1",
    "docId": "recife-logistics-airport-boa-viagem",
    "city": "Recife",
    "title": "Acesso aeroporto e Boa Viagem",
    "category": "logistics",
    "region": "Zona Sul",
    "summary": "Boa Viagem costuma reduzir tempo de deslocamento de chegada e saida.",
    "content": "Para chegadas e partidas com pouco intervalo, ficar em Boa Viagem tende a simplificar a logistica pelo acesso mais direto ao aeroporto. Em dias com agenda apertada, isso pode reduzir risco de atraso.",
    "snippet": "Boa Viagem costuma reduzir tempo de deslocamento de chegada e saida. Para chegadas e partidas com pouco intervalo, ficar em Boa Viagem tende a simplificar a logistica pelo acesso mais direto ao aeroporto. Em dias com agenda apertada, isso pode reduzir risco de atraso.",
    "tags": [
      "aeroporto",
      "deslocamento",
      "logistica"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-logistics-praia-boa-viagem-cuidados-chunk-1",
    "docId": "recife-logistics-praia-boa-viagem-cuidados",
    "city": "Recife",
    "title": "Cuidados na praia de Boa Viagem",
    "category": "logistics",
    "region": "Boa Viagem",
    "summary": "Orientacoes praticas para banho e uso da faixa de areia.",
    "content": "Ao planejar tempo de praia em Boa Viagem, consulte sinalizacao local e orientacoes publicas sobre trechos recomendados para banho. Em planejamento de roteiro, registre essa etapa como atividade com cuidado adicional.",
    "snippet": "Orientacoes praticas para banho e uso da faixa de areia. Ao planejar tempo de praia em Boa Viagem, consulte sinalizacao local e orientacoes publicas sobre trechos recomendados para banho. Em planejamento de roteiro, registre essa etapa como atividade com cuidado adicional.",
    "tags": [
      "praia",
      "seguranca",
      "cuidados"
    ],
    "source": "manual:recife-v1",
    "updatedAt": "2026-03-20"
  },
  {
    "chunkId": "recife-attraction-paco-do-frevo-chunk-1",
    "docId": "recife-attraction-paco-do-frevo",
    "city": "Recife",
    "title": "Paço do Frevo",
    "category": "attraction",
    "region": "Bairro do Recife Antigo",
    "summary": "O Paço do Frevo e um museu que preserva a cultura do frevo, um estilo de música e danca típico da região.",
    "content": "O Paço do Frevo fica localizado no Bairro do Recife Antigo, em Recife. O museu oferece exposicoes sobre a historia do frevo, bem como shows e eventos culturais ao longo do ano.",
    "snippet": "O Paço do Frevo e um museu que preserva a cultura do frevo, um estilo de música e danca típico da região. O Paço do Frevo fica localizado no Bairro do Recife Antigo, em Recife. O museu oferece exposicoes sobre a historia do frevo, bem como shows e eventos culturais ao longo do ano.",
    "tags": [
      "frevo",
      "museu",
      "recife antigo"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-food_cafe-mercado-de-sao-jose-chunk-1",
    "docId": "recife-food_cafe-mercado-de-sao-jose",
    "city": "Recife",
    "title": "Mercado de São José",
    "category": "food_cafe",
    "region": "Centro",
    "summary": "Mercado tradicional com variedade de produtos frescos e artesanais.",
    "content": "O Mercado de São José oferece uma experiencia gastronomica autentica com produtos frescos e artesanais. Visite e descubra as delicasidades locais, como frutas, legumes e produtos de panificacao.",
    "snippet": "Mercado tradicional com variedade de produtos frescos e artesanais. O Mercado de São José oferece uma experiencia gastronomica autentica com produtos frescos e artesanais. Visite e descubra as delicasidades locais, como frutas, legumes e produtos de panificacao.",
    "tags": [
      "mercado tradicional",
      "produtos frescos",
      "gastronomia local"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-torre-malakoff-chunk-1",
    "docId": "recife-attraction-torre-malakoff",
    "city": "Recife",
    "title": "Torre Malakoff",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Torre de ferro fundido construida em 1855, simbolizando a arquitetura militar do Imperio.",
    "content": "A Torre Malakoff foi construida em 1855 e e um dos principais pontos turisticos da cidade. Ela foi projetada para ser uma fortaleza, mas hoje e um simbolo da arquitetura militar do Imperio. O local oferece uma vista panoramica da cidade e e um local popular para fotos.",
    "snippet": "Torre de ferro fundido construida em 1855, simbolizando a arquitetura militar do Imperio. A Torre Malakoff foi construida em 1855 e e um dos principais pontos turisticos da cidade. Ela foi projetada para ser uma fortaleza, mas hoje e um simbolo da arquitetura militar do Imperio.",
    "tags": [
      "torre malakoff",
      "recife antigo",
      "arquitetura militar"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-torre-malakoff-chunk-2",
    "docId": "recife-attraction-torre-malakoff",
    "city": "Recife",
    "title": "Torre Malakoff",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Torre de ferro fundido construida em 1855, simbolizando a arquitetura militar do Imperio.",
    "content": "A Torre Malakoff foi construida em 1855 e e um dos principais pontos turisticos da cidade. Ela foi projetada para ser uma fortaleza, mas hoje e um simbolo da arquitetura militar do Imperio. O local oferece uma vista panoramica da cidade e e um local popular para fotos.",
    "snippet": "za, mas hoje e um simbolo da arquitetura militar do Imperio. O local oferece uma vista panoramica da cidade e e um local popular para fotos.",
    "tags": [
      "torre malakoff",
      "recife antigo",
      "arquitetura militar"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-patio-de-sao-pedro-chunk-1",
    "docId": "recife-attraction-patio-de-sao-pedro",
    "city": "Recife",
    "title": "Pátio de São Pedro",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Praça histórica e ponto de encontro no centro antigo de Recife.",
    "content": "O Pátio de São Pedro é um local emblemático da cidade, conhecido por suas ruas estreitas e arquitetura colonial. É um ótimo lugar para se perder e descobrir a história de Recife.",
    "snippet": "Praça histórica e ponto de encontro no centro antigo de Recife. O Pátio de São Pedro é um local emblemático da cidade, conhecido por suas ruas estreitas e arquitetura colonial. É um ótimo lugar para se perder e descobrir a história de Recife.",
    "tags": [
      "centro historico",
      "recife antigo",
      "patrimonio cultural"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-mamam-chunk-1",
    "docId": "recife-attraction-mamam",
    "city": "Recife",
    "title": "MAMAM - Museu de Arte Moderna Aloísio Magalhães",
    "category": "attraction",
    "region": "Boa Vista",
    "summary": "O MAMAM é um museu de arte moderna localizado no bairro de Boa Vista, em Recife.",
    "content": "O MAMAM é um dos principais museus de arte moderna da cidade de Recife. O museu conta com uma coleção de obras de artistas brasileiros e internacionais, além de exposições temporárias.",
    "snippet": "O MAMAM é um museu de arte moderna localizado no bairro de Boa Vista, em Recife. O MAMAM é um dos principais museus de arte moderna da cidade de Recife. O museu conta com uma coleção de obras de artistas brasileiros e internacionais, além de exposições temporárias.",
    "tags": [
      "arte moderna",
      "museu",
      "recife"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-casa-da-cultura-de-pernambuco-chunk-1",
    "docId": "recife-attraction-casa-da-cultura-de-pernambuco",
    "city": "Recife",
    "title": "Casa da Cultura de Pernambuco",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Instituicao cultural que promove eventos e exposicoes de arte e cultura.",
    "content": "A Casa da Cultura de Pernambuco fica no Recife Antigo, oferecendo exposicoes de arte, eventos culturais e atividades para visitantes. O local e um ponto de encontro para a comunidade cultural da cidade.",
    "snippet": "Instituicao cultural que promove eventos e exposicoes de arte e cultura. A Casa da Cultura de Pernambuco fica no Recife Antigo, oferecendo exposicoes de arte, eventos culturais e atividades para visitantes. O local e um ponto de encontro para a comunidade cultural da cidade.",
    "tags": [
      "arte",
      "cultura",
      "recife antigo"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-teatro-santa-isabel-chunk-1",
    "docId": "recife-attraction-teatro-santa-isabel",
    "city": "Recife",
    "title": "Teatro Santa Isabel",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Teatro historicamente importante, localizado no Recife Antigo.",
    "content": "O Teatro Santa Isabel foi fundado em 1850 e e um dos mais antigos teatros do Brasil. O local oferece apresentacoes culturais e eventos ao longo do ano.",
    "snippet": "Teatro historicamente importante, localizado no Recife Antigo. O Teatro Santa Isabel foi fundado em 1850 e e um dos mais antigos teatros do Brasil. O local oferece apresentacoes culturais e eventos ao longo do ano.",
    "tags": [
      "teatro",
      "recife antigo",
      "cultura"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-sinagoga-kahal-zur-israel-chunk-1",
    "docId": "recife-attraction-sinagoga-kahal-zur-israel",
    "city": "Recife",
    "title": "Sinagoga Kahal Zur Israel",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Uma das sinagogas mais antigas do Brasil, construida em 1636.",
    "content": "A Sinagoga Kahal Zur Israel fica na Rua do Bom Jesus, no bairro do Recife Antigo. O local e um importante marco historico da comunidade judaica em Recife e um destino imperdível para visitantes interessados em historia e cultura.",
    "snippet": "Uma das sinagogas mais antigas do Brasil, construida em 1636. A Sinagoga Kahal Zur Israel fica na Rua do Bom Jesus, no bairro do Recife Antigo. O local e um importante marco historico da comunidade judaica em Recife e um destino imperdível para visitantes interessados em historia e cultura.",
    "tags": [
      "sinagoga",
      "recife antigo",
      "historia judaica"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-parque-estadual-de-dois-irmaos-chunk-1",
    "docId": "recife-attraction-parque-estadual-de-dois-irmaos",
    "city": "Recife",
    "title": "Parque Estadual de Dois Irmãos",
    "category": "attraction",
    "region": "Zona da Mata",
    "summary": "Parque estadual com vegetacao atlantica e trilhas para caminhada.",
    "content": "O Parque Estadual de Dois Irmãos oferece trilhas para caminhada, observacao de aves e vegetacao atlantica. O local e conhecido por suas belezas naturais e diversidade de especies.",
    "snippet": "Parque estadual com vegetacao atlantica e trilhas para caminhada. O Parque Estadual de Dois Irmãos oferece trilhas para caminhada, observacao de aves e vegetacao atlantica. O local e conhecido por suas belezas naturais e diversidade de especies.",
    "tags": [
      "parque estadual",
      "zona da mata",
      "trilhas"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-praca-da-republica-chunk-1",
    "docId": "recife-attraction-praca-da-republica",
    "city": "Recife",
    "title": "Praça da República",
    "category": "attraction",
    "region": "Centro",
    "summary": "Praça central da cidade, com arquitetura colonial e eventos culturais.",
    "content": "A Praça da República é um local importante para eventos culturais e políticos em Recife. Ela é cercada por edifícios históricos e oferece uma atmosfera única para visitantes.",
    "snippet": "Praça central da cidade, com arquitetura colonial e eventos culturais. A Praça da República é um local importante para eventos culturais e políticos em Recife. Ela é cercada por edifícios históricos e oferece uma atmosfera única para visitantes.",
    "tags": [
      "praça central",
      "centro historico",
      "eventos culturais"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-museu-do-trem-do-recife-chunk-1",
    "docId": "recife-attraction-museu-do-trem-do-recife",
    "city": "Recife",
    "title": "Museu do Trem do Recife",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Museu que preserva e expoe equipamentos e historias do transporte ferroviario no estado de Pernambuco.",
    "content": "O Museu do Trem do Recife fica localizado no antigo terminal ferroviario da cidade, na area historica do Recife Antigo. O museu conta a historia da ferrovia no estado e expoe equipamentos e veiculos de transporte ferroviario.",
    "snippet": "Museu que preserva e expoe equipamentos e historias do transporte ferroviario no estado de Pernambuco. O Museu do Trem do Recife fica localizado no antigo terminal ferroviario da cidade, na area historica do Recife Antigo.",
    "tags": [
      "museu",
      "recife antigo",
      "ferrovia"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-museu-do-trem-do-recife-chunk-2",
    "docId": "recife-attraction-museu-do-trem-do-recife",
    "city": "Recife",
    "title": "Museu do Trem do Recife",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Museu que preserva e expoe equipamentos e historias do transporte ferroviario no estado de Pernambuco.",
    "content": "O Museu do Trem do Recife fica localizado no antigo terminal ferroviario da cidade, na area historica do Recife Antigo. O museu conta a historia da ferrovia no estado e expoe equipamentos e veiculos de transporte ferroviario.",
    "snippet": "l ferroviario da cidade, na area historica do Recife Antigo. O museu conta a historia da ferrovia no estado e expoe equipamentos e veiculos de transporte ferroviario.",
    "tags": [
      "museu",
      "recife antigo",
      "ferrovia"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-oficina-de-ceramica-francisco-brennand-chunk-1",
    "docId": "recife-attraction-oficina-de-ceramica-francisco-brennand",
    "city": "Recife",
    "title": "Oficina de Cerâmica Francisco Brennand",
    "category": "attraction",
    "region": "Itaparica",
    "summary": "Local de criacao de obras de arte em ceramica, com exposicoes e venda de produtos.",
    "content": "A Oficina de Cerâmica Francisco Brennand fica localizada no Parque Artesanal de Itaparica, em Recife. O local oferece exposicoes de obras de arte em ceramica, venda de produtos e atividades de criacao de arte.",
    "snippet": "Local de criacao de obras de arte em ceramica, com exposicoes e venda de produtos. A Oficina de Cerâmica Francisco Brennand fica localizada no Parque Artesanal de Itaparica, em Recife. O local oferece exposicoes de obras de arte em ceramica, venda de produtos e atividades de criacao de arte.",
    "tags": [
      "ceramica",
      "arte",
      "itaparica"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-attraction-basilica-de-nossa-senhora-do-carmo-chunk-1",
    "docId": "recife-attraction-basilica-de-nossa-senhora-do-carmo",
    "city": "Recife",
    "title": "Basílica de Nossa Senhora do Carmo",
    "category": "attraction",
    "region": "Recife Antigo",
    "summary": "Igreja catolica com arquitetura colonial e importancia religiosa.",
    "content": "A Basílica de Nossa Senhora do Carmo fica no Recife Antigo, uma das areas mais historicas da cidade. O local oferece uma experiencia religiosa e cultural, com arquitetura colonial e artefatos religiosos.",
    "snippet": "Igreja catolica com arquitetura colonial e importancia religiosa. A Basílica de Nossa Senhora do Carmo fica no Recife Antigo, uma das areas mais historicas da cidade. O local oferece uma experiencia religiosa e cultural, com arquitetura colonial e artefatos religiosos.",
    "tags": [
      "recife antigo",
      "igreja catolica",
      "arte religioso"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-neighborhood-espinheiro-chunk-1",
    "docId": "recife-neighborhood-espinheiro",
    "city": "Recife",
    "title": "Espinheiro",
    "category": "neighborhood",
    "region": "Zona Norte",
    "summary": "Bairro residencial com comércio local e acesso a parques.",
    "content": "O Espinheiro é um bairro residencial da Zona Norte de Recife, conhecido por sua vida noturna e comércio local. A região oferece acesso a parques e áreas verdes, além de opções de lazer e entretenimento.",
    "snippet": "Bairro residencial com comércio local e acesso a parques. O Espinheiro é um bairro residencial da Zona Norte de Recife, conhecido por sua vida noturna e comércio local. A região oferece acesso a parques e áreas verdes, além de opções de lazer e entretenimento.",
    "tags": [
      "zona norte",
      "bairro residencial",
      "comercio local"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-neighborhood-madalena-chunk-1",
    "docId": "recife-neighborhood-madalena",
    "city": "Recife",
    "title": "Madalena",
    "category": "neighborhood",
    "region": "Zona Norte",
    "summary": "Bairro popular conhecido por suas ruas estreitas e casas antigas.",
    "content": "A Madalena e um dos bairros mais antigos de Recife, conhecido por suas ruas estreitas e casas antigas. O bairro e um destino popular para visitantes que procuram uma experiencia autentica da cidade.",
    "snippet": "Bairro popular conhecido por suas ruas estreitas e casas antigas. A Madalena e um dos bairros mais antigos de Recife, conhecido por suas ruas estreitas e casas antigas. O bairro e um destino popular para visitantes que procuram uma experiencia autentica da cidade.",
    "tags": [
      "bairro antigo",
      "ruas estreitas",
      "casa antiga"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-neighborhood-gracas-chunk-1",
    "docId": "recife-neighborhood-gracas",
    "city": "Recife",
    "title": "Graças",
    "category": "neighborhood",
    "region": "Zona Norte",
    "summary": "Bairro residencial com comércio local e acesso a pontos turísticos.",
    "content": "A Graças é um bairro residencial da Zona Norte de Recife, conhecido por sua vida noturna e comércio local. O bairro é acessível a pé ou de ônibus e oferece opções de restaurantes e bares.",
    "snippet": "Bairro residencial com comércio local e acesso a pontos turísticos. A Graças é um bairro residencial da Zona Norte de Recife, conhecido por sua vida noturna e comércio local. O bairro é acessível a pé ou de ônibus e oferece opções de restaurantes e bares.",
    "tags": [
      "bairro residencial",
      "comercio local",
      "vida noturna"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-food_cafe-burburinho-gastronomia-chunk-1",
    "docId": "recife-food_cafe-burburinho-gastronomia",
    "city": "Recife",
    "title": "Burburinho Gastronomia",
    "category": "food_cafe",
    "region": "Boa Vista",
    "summary": "Restaurante com comida brasileira e internacional, conhecido por sua variedade de opções.",
    "content": "O Burburinho Gastronomia oferece uma variedade de pratos, incluindo opções vegetarianas e veganas. O local é conhecido por sua atmosfera aconchegante e serviço atencioso.",
    "snippet": "Restaurante com comida brasileira e internacional, conhecido por sua variedade de opções. O Burburinho Gastronomia oferece uma variedade de pratos, incluindo opções vegetarianas e veganas. O local é conhecido por sua atmosfera aconchegante e serviço atencioso.",
    "tags": [
      "comida brasileira",
      "opcoes vegetarianas",
      "atmosfera aconchegante"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-neighborhood-bargaco-recife-chunk-1",
    "docId": "recife-neighborhood-bargaco-recife",
    "city": "Recife",
    "title": "Bargaço Recife",
    "category": "neighborhood",
    "region": "Bairro do Bargaço",
    "summary": "Bairro residencial e comercial, conhecido por suas ruas arborizadas e vida noturna.",
    "content": "O Bargaço Recife é um bairro residencial e comercial da cidade, conhecido por suas ruas arborizadas e vida noturna. É um local popular para morar e visitar, com muitas opções de lazer e entretenimento.",
    "snippet": "Bairro residencial e comercial, conhecido por suas ruas arborizadas e vida noturna. O Bargaço Recife é um bairro residencial e comercial da cidade, conhecido por suas ruas arborizadas e vida noturna. É um local popular para morar e visitar, com muitas opções de lazer e entretenimento.",
    "tags": [
      "bairro residencial",
      "comercio local",
      "vida noturna"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-food_cafe-chica-pitanga-chunk-1",
    "docId": "recife-food_cafe-chica-pitanga",
    "city": "Recife",
    "title": "Chica Pitanga",
    "category": "food_cafe",
    "region": "Boa Vista",
    "summary": "Restaurante com comida brasileira e ambiente aconchegante.",
    "content": "A Chica Pitanga oferece pratos típicos brasileiros em um ambiente acolhedor. O local é conhecido por sua comida caseira e opções vegetarianas.",
    "snippet": "Restaurante com comida brasileira e ambiente aconchegante. A Chica Pitanga oferece pratos típicos brasileiros em um ambiente acolhedor. O local é conhecido por sua comida caseira e opções vegetarianas.",
    "tags": [
      "comida brasileira",
      "restaurante",
      "boavista"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-food_cafe-lapinha-gastronomia-chunk-1",
    "docId": "recife-food_cafe-lapinha-gastronomia",
    "city": "Recife",
    "title": "Lapinha Gastronomia",
    "category": "food_cafe",
    "region": "Boa Vista",
    "summary": "Restaurante com comida brasileira e internacional, conhecido por sua variedade de opções.",
    "content": "O Lapinha Gastronomia oferece uma variedade de pratos, incluindo opções vegetarianas e veganas. O ambiente é acolhedor e a equipe é atenciosa.",
    "snippet": "Restaurante com comida brasileira e internacional, conhecido por sua variedade de opções. O Lapinha Gastronomia oferece uma variedade de pratos, incluindo opções vegetarianas e veganas. O ambiente é acolhedor e a equipe é atenciosa.",
    "tags": [
      "comida brasileira",
      "opcoes vegetarianas",
      "restaurante"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  },
  {
    "chunkId": "recife-logistics-metro-do-recife-chunk-1",
    "docId": "recife-logistics-metro-do-recife",
    "city": "Recife",
    "title": "Metrô do Recife",
    "category": "logistics",
    "region": "Recife",
    "summary": "Sistema de transporte metroviario que atende a cidade de Recife.",
    "content": "O Metrô do Recife e uma das principais opcoes de transporte publico da cidade. Com linhas que atendem a varios bairros, o metrô facilita o deslocamento de pessoas pelo Recife.",
    "snippet": "Sistema de transporte metroviario que atende a cidade de Recife. O Metrô do Recife e uma das principais opcoes de transporte publico da cidade. Com linhas que atendem a varios bairros, o metrô facilita o deslocamento de pessoas pelo Recife.",
    "tags": [
      "transporte publico",
      "recife",
      "metrô"
    ],
    "source": "llm-draft:recife-v1-expansion",
    "updatedAt": "2026-03-29"
  }
]
